name: tests and linters
on:
  push:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.13"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Linters
      run: make linters
    - name: Tests
      run: |
        make test
